name: Build and push Docker images

on:
  workflow_call:
    inputs:
      registry:
        type: string
        required: true
        default: 'ghcr.io'
      latest:
        type: string
        required: true
        default: 'auto'
      prefix:
        type: string
        required: false
        default: ''
      suffix:
        type: string
        required: false
        default: ''
      target:
        type: string
        required: false
        default: ''

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ github.repository }}
          flavor:
            latest: ${{ inputs.latest }}
            prefix: ${{ inputs.prefix }}
            suffix: ${{ inputs.suffix }}
      -
        name: Login to GitHub Container Registry          
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          network: host
          push: true
          tags: ${{ inputs.registry }}/${{ steps.meta.outputs.tags }}
          target: ${{ inputs.target }}
