name: Build and push Docker images

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      -
        name: Get Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          network: host
          push: true
          tags: ghcr.io/${{ steps.meta.outputs.tags }}
